version: '3.8'

services:
  webapp:
    build: .
    ports:
      - "8000:8080"
    environment:
      PORT: 8080
      DATASTORE: ${DATASTORE}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      BEARER_TOKEN: ${BEARER_TOKEN}
      CHROMA_IN_MEMORY: ${CHROMA_IN_MEMORY}
      CHROMA_PERSISTENCE_DIR: ${CHROMA_PERSISTENCE_DIR}
    volumes:
      - .:/code
      - storage-volume:/storage

  caddy:
    image: caddy:2
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app

volumes:
  storage-volume:
  caddy_data:
  caddy_config: