version: '3.8'

services:
  webapp:
    build: .
    ports:
      - "8000:8080"
    environment:
      PORT: 8080
      DATASTORE: ${DATASTORE}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      BEARER_TOKEN: ${BEARER_TOKEN}
      CHROMA_IN_MEMORY: ${CHROMA_IN_MEMORY}
      CHROMA_PERSISTENCE_DIR: ${CHROMA_PERSISTENCE_DIR}
    volumes:
      - .:/code
      - storage-volume:/storage

volumes:
  storage-volume: